loadListeningData({
    type: "listening",
    navName: "Listening",
    name: "Part II Listening Comprehension (25 minutes)",
    groups: [
        // ============================================================
        // Section A: Conversation 1 — AI Courses vs Traditional Courses
        // ============================================================
        {
            "title": "Section A: Conversation 1",
            "script": "W: Hey Tom, have you registered for next semester\u2019s courses yet?\n\nM: Not yet, I\u2019m still debating. My advisor is pushing me toward the new AI and Machine Learning concentration, but I kind of wanted to take a few more traditional literature seminars.\n\nW: I know what you mean. Everyone\u2019s talking about AI these days. The department head said that within five years, AI literacy will be as fundamental as math. But I feel like the classics still have value.\n\nM: Exactly! I love the deep discussions in Professor Harris\u2019s 19th-century novel course. You don\u2019t get that kind of nuanced human insight from a neural network. On the other hand, I look at the job market and worry.\n\nW: That\u2019s the dilemma isn\u2019t it? I actually spoke to a recruiter from TechBridge last week. She said they\u2019re hiring humanities graduates specifically because they can think critically and communicate well. But they also expect basic AI familiarity.\n\nM: So maybe a hybrid approach is the way to go. Take the core AI course for foundational skills and keep the literature seminar as an elective.\n\nW: That sounds reasonable. You\u2019d get the technical edge without sacrificing the education you actually want.\n\nM: Yeah, I think I\u2019ll go with that plan. The AI course is on Tuesday evenings, and the literature seminar is on Thursday afternoons, so they don\u2019t even conflict timewise.\n\nW: Perfect. Looks like you\u2019ve made up your mind then.",
            "questions": [
                { "id": 1, "options": ["A) He has already registered for both courses.", "B) His advisor fully supports his choice of literature courses.", "C) He is struggling to decide between AI and literature courses.", "D) He has decided to drop out of the AI course."], "answer": "C" },
                { "id": 2, "options": ["A) Literature courses offer no practical value.", "B) The classics provide deep human insight not found in AI.", "C) AI courses are a waste of time.", "D) Professor Harris discourages students from taking AI courses."], "answer": "B" },
                { "id": 3, "options": ["A) They only hire candidates with engineering degrees.", "B) They pay higher salaries than most tech companies.", "C) They value humanities graduates who also have basic AI knowledge.", "D) They have stopped recruiting from universities altogether."], "answer": "C" },
                { "id": 4, "options": ["A) Drop the literature seminar entirely.", "B) Take both the AI course and the literature seminar.", "C) Switch to an entirely AI-focused curriculum.", "D) Postpone the decision until next semester."], "answer": "B" }
            ]
        },

        // ============================================================
        // Section A: Conversation 2 — Remote Work Discussion
        // ============================================================
        {
            "title": "Section A: Conversation 2",
            "script": "M: Good morning, Sarah. How\u2019s the new remote arrangement working out for your team?\n\nW: Morning, David. It\u2019s been a mixed bag, honestly. Productivity metrics are actually up by about 12 percent, but I\u2019m starting to see some cracks in team cohesion.\n\nM: That\u2019s interesting. Our department has been fully remote for six months now, and while people love the flexibility, I\u2019ve noticed junior staff are struggling without the informal mentorship that happens in an office environment.\n\nW: Exactly the issue I\u2019m seeing! New hires are technically proficient, but they don\u2019t absorb the unwritten rules of the company culture. Water-cooler conversations and overheard phone calls actually teach a lot about how decisions really get made.\n\nM: Right. I spoke with HR about implementing a buddy system, pairing each junior employee with a senior mentor for weekly one-on-one video calls. Not just for project oversight, but for career guidance.\n\nW: That\u2019s a good start. We\u2019ve also started doing monthly in-person meetups, not mandatory, but well attended. People are hungry for face-to-face interaction.\n\nM: Has management been supportive of the costs?\n\nW: Surprisingly, yes. They crunched the numbers and realized the savings on office space far outweigh the travel and event expenses. Plus, retention has improved, so recruitment costs are down.\n\nM: So it sounds like the key is intentional community building. You can\u2019t just say \u201cwork from home\u201d and hope culture survives on its own.\n\nW: Precisely. Remote work isn\u2019t the problem, it\u2019s the lack of intentionality that causes issues.",
            "questions": [
                { "id": 5, "options": ["A) Productivity has decreased.", "B) Team cohesion is suffering.", "C) Office costs have gone up.", "D) Senior staff have all resigned."], "answer": "B" },
                { "id": 6, "options": ["A) They lack technical skills.", "B) They are not given enough assignments.", "C) They miss informal mentorship and company culture cues.", "D) They prefer working in the office."], "answer": "C" },
                { "id": 7, "options": ["A) A mandatory return-to-office policy.", "B) A buddy system pairing juniors with senior mentors.", "C) Reducing video calls to improve focus.", "D) Hiring more senior managers."], "answer": "B" },
                { "id": 8, "options": ["A) The costs are too high for the company.", "B) Attendance for in-person meetups is very low.", "C) The savings on office space outweigh the event costs.", "D) Management is planning to end remote work entirely."], "answer": "C" }
            ]
        },

        // ============================================================
        // Section B: Passage 1 — Space Tourism
        // ============================================================
        {
            "title": "Section B: Passage 1",
            "script": "The dream of space travel has captivated humanity for generations, but until recently, it remained the exclusive domain of professionally trained astronauts. That landscape is changing rapidly. Over the past few years, several private companies have successfully launched civilian passengers into suborbital and even orbital space, marking the dawn of a new era in tourism.\n\nHowever, space tourism is not without its controversies. Critics point out the astronomical environmental cost. A single rocket launch can emit as much carbon dioxide as a transatlantic flight times several hundred. For a luxury experience enjoyed by only a handful of ultra-wealthy individuals, the carbon footprint is hard to justify.\n\nProponents argue that these early commercial flights are essentially research and development investments. The technology being tested today will eventually lead to more efficient propulsion systems, lower costs, and routine commercial space travel, much like how early aviation was once considered a dangerous luxury before becoming accessible to the masses.\n\nSafety remains the greatest concern. While companies have implemented rigorous testing protocols, the inherent risks of spaceflight are significantly higher than those of commercial aviation. Passengers must undergo weeks of training and pass medical evaluations that would disqualify many ordinary travelers. As the industry matures, regulatory frameworks will need to evolve to ensure that safety standards keep pace with commercial ambitions.",
            "questions": [
                { "id": 9, "options": ["A) It has been widely available for decades.", "B) It was previously limited to trained astronauts.", "C) It is regulated by an international space agency.", "D) It costs about the same as first-class air travel."], "answer": "B" },
                { "id": 10, "options": ["A) The lack of interested passengers.", "B) The difficulty of rocket engineering.", "C) The high carbon emissions of each launch.", "D) The shortage of qualified pilots."], "answer": "C" },
                { "id": 11, "options": ["A) They are a luxury with no practical purpose.", "B) They are investments that will make space travel more accessible over time.", "C) They should be banned until safety improves.", "D) They are primarily funded by government space agencies."], "answer": "B" }
            ]
        },

        // ============================================================
        // Section B: Passage 2 — Urban Greening
        // ============================================================
        {
            "title": "Section B: Passage 2",
            "script": "As cities around the world grapple with rising temperatures and increasingly frequent extreme weather events, urban greening has emerged as one of the most cost-effective strategies for climate adaptation. Green roofs, vertical gardens, and urban parks do more than beautify a cityscape; they actively cool surrounding areas, absorb storm-water runoff, and improve air quality.\n\nA landmark study conducted in Singapore tracked temperature differences between areas with high vegetation density and those dominated by concrete and asphalt. The green neighborhoods were on average three to four degrees Celsius cooler during the hottest months. The cooling effect comes from two mechanisms: shade provided by tree canopies and evapotranspiration, the process by which plants release water vapor into the air.\n\nBeyond temperature regulation, urban greening projects also provide measurable mental health benefits. Researchers have found that access to green spaces reduces stress hormones, improves concentration, and even accelerates recovery times for hospital patients. City planners are increasingly incorporating these findings into zoning regulations, with some municipalities now requiring a minimum percentage of green space in all new developments.\n\nThe challenge, however, lies in maintenance. Green infrastructure requires ongoing care, watering systems, and periodic replacement of plants. Cities with limited budgets often struggle to maintain these spaces once the initial installation is complete. Nevertheless, the long-term benefits in reduced energy costs, improved public health, and climate resilience make urban greening an investment that pays for itself many times over.",
            "questions": [
                { "id": 12, "options": ["A) It is too expensive for most cities.", "B) It primarily improves the appearance of buildings.", "C) It helps cool cities and manage storm-water.", "D) It has no measurable effect on public health."], "answer": "C" },
                { "id": 13, "options": ["A) They were about the same temperature.", "B) Green neighborhoods were significantly cooler.", "C) Concrete areas had more vegetation.", "D) The temperature difference was negligible."], "answer": "B" },
                { "id": 14, "options": ["A) The high initial construction costs.", "B) The ongoing maintenance and care required.", "C) The lack of suitable plant species.", "D) The opposition from local residents."], "answer": "B" }
            ]
        },

        // ============================================================
        // Section C: Lecture 1 — Sleep Science
        // ============================================================
        {
            "title": "Section C: Lecture 1",
            "script": "Good morning everyone. Today we\u2019re going to explore one of the most fascinating yet misunderstood aspects of human biology: sleep. Despite spending roughly one third of our lives asleep, we are only beginning to understand why sleep is so essential.\n\nLet\u2019s start with the sleep cycle. A normal night of sleep consists of four to six cycles, each lasting about ninety minutes. Each cycle includes two main phases: non-REM sleep and REM sleep, which stands for rapid eye movement. Non-REM sleep itself is divided into three stages: N1, a light sleep where you can be easily awakened; N2, where your body temperature drops and heart rate slows; and N3, also known as deep sleep or slow-wave sleep, which is crucial for physical restoration.\n\nREM sleep, on the other hand, is when most of our dreaming occurs. During this phase, the brain is almost as active as when we are awake, but the body is temporarily paralyzed, a mechanism that prevents us from acting out our dreams. REM sleep plays a critical role in emotional regulation and memory consolidation.\n\nRecent research has uncovered something remarkable: during deep sleep, the brain actually clears out waste products that accumulate during the day. A team at the University of Rochester discovered that the glymphatic system, a kind of cleaning network in the brain, becomes ten times more active during sleep. This process flushes out proteins like beta-amyloid, which is associated with Alzheimer\u2019s disease. This finding has led scientists to investigate whether chronic sleep deprivation might be linked to a higher risk of neurodegenerative conditions.\n\nSo what does this mean for you? Prioritizing quality sleep isn\u2019t a luxury, it\u2019s a biological necessity. Aim for seven to nine hours per night, maintain a consistent sleep schedule, and limit exposure to blue light from screens before bed. Your brain will thank you.",
            "questions": [
                { "id": 15, "options": ["A) It consists of two stages: light sleep and deep sleep.", "B) It includes 7 to 9 cycles per night.", "C) Each cycle lasts roughly 90 minutes with several phases.", "D) It has only one phase that repeats throughout the night."], "answer": "C" },
                { "id": 16, "options": ["A) It decreases brain activity to almost zero.", "B) It is when the body is most physically active.", "C) It paralyzes the body temporarily while the brain stays active.", "D) It prevents long-term memory formation."], "answer": "C" },
                { "id": 17, "options": ["A) It processes visual information from the day.", "B) It clears waste products and flushes out harmful proteins.", "C) It strengthens the immune system against infections.", "D) It repairs damaged muscle tissue."], "answer": "B" }
            ]
        },

        // ============================================================
        // Section C: Lecture 2 — Language Learning Mechanisms
        // ============================================================
        {
            "title": "Section C: Lecture 2",
            "script": "Today I\u2019d like to discuss how human beings acquire language, a question that has puzzled linguists and psychologists for centuries. While children seem to pick up their native language effortlessly, adults often struggle to achieve fluency in a second language. Why is that?\n\nOne influential theory comes from linguist Noam Chomsky, who proposed that humans are born with an innate language acquisition device, or LAD, a hypothetical brain structure dedicated to processing language. According to Chomsky, this biological endowment explains why children universally reach linguistic milestones at roughly the same ages, regardless of the specific language they are exposed to.\n\nHowever, more recent research suggests that the picture is more complex. Neuroimaging studies have revealed that language learning involves a distributed network of brain regions, including Broca\u2019s area for speech production and Wernicke\u2019s area for comprehension, but also areas associated with memory, social cognition, and even motor control.\n\nA key factor in language acquisition is what researchers call the critical period hypothesis. This proposes that there is an optimal window during childhood, roughly up to puberty, during which the brain is especially receptive to language input. After this period, the brain\u2019s plasticity decreases, making it harder to achieve native-like proficiency in a new language. This doesn\u2019t mean adults can\u2019t learn new languages, they absolutely can, but the neural pathways are less flexible.\n\nImmersion appears to be the most effective method for adult learners. Studies show that adults who live in a country where the target language is spoken and actively engage with native speakers on a daily basis make faster progress than those who only study in a classroom setting. The reason is that real-world communication requires rapid processing, negotiation of meaning, and exposure to authentic, unscripted language, all of which strengthen neural connections in ways that textbook exercises cannot replicate.",
            "questions": [
                { "id": 18, "options": ["A) It is entirely learned through imitation.", "B) Humans are born with an innate biological capacity for language.", "C) Language acquisition depends only on social interaction.", "D) Different languages activate completely different brain regions."], "answer": "B" },
                { "id": 19, "options": ["A) The brain remains equally plastic throughout life.", "B) Children have faster vocal cords.", "C) The brain\u2019s plasticity decreases after puberty.", "D) Adults have fewer memory capacities."], "answer": "C" },
                { "id": 20, "options": ["A) Grammar drills.", "B) Classroom textbook study.", "C) Immersion in a native-speaking environment.", "D) Learning through translation only."], "answer": "C" }
            ]
        },

        // ============================================================
        // Section C: Lecture 3 — Social Media and Teenagers
        // ============================================================
        {
            "title": "Section C: Lecture 3",
            "script": "In today\u2019s lecture, we will examine the complex relationship between social media and adolescent development. With over ninety percent of teenagers in developed countries reporting daily social media use, understanding its effects has become one of the most pressing issues in developmental psychology.\n\nLet\u2019s begin with the positive aspects. Social media provides teenagers with a sense of belonging and social support, particularly for those who feel marginalized in their offline lives. LGBTQ+ youth, for example, often find communities online where they can connect with peers who share similar experiences. Social platforms also offer access to educational content, creative outlets, and opportunities for civic engagement.\n\nHowever, the negative effects are equally significant and well-documented. A landmark longitudinal study tracking over twelve thousand adolescents in the United Kingdom found a strong correlation between heavy social media use and increased rates of anxiety and depression, particularly among girls. The researchers identified social comparison as the primary driver: teenagers constantly compare their own lives to the curated, idealized versions they see on their peers\u2019 feeds.\n\nAnother concern is the impact on sleep. The blue light emitted by screens suppresses melatonin production, making it harder to fall asleep. When teenagers scroll through social media late into the night, they not only lose sleep quantity but also disrupt the quality of their sleep cycles. The study I mentioned earlier found that sleep deprivation mediated nearly half of the negative mental health effects associated with social media use.\n\nWhat can parents and educators do? The evidence suggests that complete abstinence is neither realistic nor necessary. Instead, the most effective approach involves setting boundaries, such as no phones during meals and an hour before bedtime, and encouraging critical media literacy so that teenagers can recognize manipulative design features and curated content for what they are. Digital literacy education should be integrated into school curricula starting from an early age.",
            "questions": [
                { "id": 21, "options": ["A) It provides no benefits for teenagers.", "B) It mainly offers entertainment without social value.", "C) It can provide belonging and support for marginalized youth.", "D) Its only positive effect is educational content."], "answer": "C" },
                { "id": 22, "options": ["A) Cyberbullying.", "B) Reduced screen time.", "C) Social comparison with curated online lives.", "D) Lack of parental supervision."], "answer": "C" },
                { "id": 23, "options": ["A) Banning social media entirely.", "B) Setting boundaries and teaching critical media literacy.", "C) Allowing unlimited use to build resilience.", "D) Monitoring all online activity through software."], "answer": "B" }
            ]
        }
    ]
});
